### PR TITLE
336 chat styling bug

### PR DESCRIPTION
**Pull request by janong24**
Chat bugs fixed:

- Styling issue for received messages
- Styling issue for attachments
- Blank messages
- Unable to attach file alone
- Unable to report messages while chatting

Closes: #336

### CODE REVIEW

**Review by Chr728 — CHANGES_REQUESTED** [review]
the styling issues of the one that is sent and received are confusing and misleading please update them

**Comment by Ghaith-Chrit** [comment]
To expand on the issue. Here is a sample chat between JoeUser and JoeRecruiter when JoeUser tries to send a file to JoeRecruiter.

At the start, it looks good. This occurs before anyone attempts to refresh their page.
image

When they refresh the page, the styles are a bit misleading. This is how it looks after a refresh
JoeUser point of view:
image

JoeRecruiter point of view:
image

The expected behavior is that everything stays the same after refreshing the page. Most likely the issue is in `messagingPage.html`. All that is needed is to check if you are the sender or not and if the message content is empty/null or not and then apply the styles accordingly. You don't need to reinvent the styles, you can copy them from `main.js` since they should look the same.

**Comment by Ghaith-Chrit** [comment]
The backend looks good.

**Comment by janong24** [comment]
Cannot yet report live messages (prior to refresh).

**Review by Chr728 — APPROVED** [review]

**Pull request merged**
